controllerReturnedProfile: wartoscZPliku dev-yaml
controllerReturned: CR_nadpisany_DEV

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: Pawel
    password: root

  jpa:
    hibernate:
      #ddl-auto - enable to generate database strucutre via hibernate
        #ddl-auto: update
    properties:
      hibernate:
        #default_schema: liquibase_schema
  liquibase:
    #default-schema: liquibase_schema