spring:
  liquibase:
    change-log: classpath:changeLog.xml

  datasource:
    url: jdbc:h2:file:D:/Workspaces/LiquiBase_h2File/h2

  profiles:
    active: "prod"
controllerReturned: wartoscZPliku_yaml czesc prod

---
spring:
  liquibase:
    change-log: classpath:changeLog.xml

  datasource:
    url: jdbc:h2:file:D:/Workspaces/LiquiBase_h2File/h2

  profiles:
    active: "dev"
##controllerReturned: wartoscZPliku_yaml czesc dev
