##there is also other possible method to store all configuration in single file, or divided it to separate files
spring:
  liquibase:
    change-log: classpath:changeLog.xml

  datasource:
    url: jdbc:h2:file:D:/Workspaces/LiquiBase_h2File/h2

  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

info:
  app:
    name: My first application Paweł Toporowicz

management:
  endpoints:
    web:
      exposure:
        include: beans, caches, env


controllerReturned: wartoscZPliku_yaml czesc prod

---
spring:
  liquibase:
    change-log: classpath:changeLog.xml

  datasource:
    url: jdbc:h2:file:D:/Workspaces/LiquiBase_h2File/h2

  profiles:
    active: dev
##controllerReturned: wartoscZPliku_yaml czesc dev
