swagger: '2.0'
info:
  description: This is my controller to learn swagger.
  version: 1.0.1
  title: Pawel Toporowicz Test API
host: localhost
paths:
  /getStudentSwagSwagger:
    get:
      summary: Get regards for user.
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: StudentSwag from Get
          schema:
            $ref: '#/definitions/StudentSwag'
      responses:
        '201':
          description: OK from Get regards
  /postStudentSwagSwagger:
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Consumes from Post.
          schema:
            $ref: '#/definitions/StudentSwag'
      responses:
        '200':
          description: Ok from Post regards
  /postStudentSwagSwaggerWithResponse:
    post:
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Consumes from Post.
          schema:
            $ref: '#/definitions/StudentSwag'
      responses:
        '200':
          description: Ok from Post regards
          schema:
            $ref: '#/definitions/StudentSwag'
  /getStudentSwagSwaggerWithResponse:
    get:
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: Consumes from Post.
          schema:
            $ref: '#/definitions/StudentSwag'
      responses:
        '200':
          description: Ok from Post regards
          schema:
            $ref: '#/definitions/StudentSwag'
  /getListStudentSwagSwaggerWithResponse:
    get:
      consumes:
        - application/json
      responses:
        '200':
          description: Ok from get list of Object
          schema:
            $ref: '#/definitions/StudentSwagList'
  /getListStudentGeneratedResponse:
    get:
      responses:
        '200':
          description: generated from yaml controller
          schema:
            type: array
            items:
              $ref: '#/definitions/StudentSwag'
  /getSetStudentGeneratedResponse:
    get:
      responses:
        '200':
          description: generated from yaml controller
          schema:
            type: array
            items:
              type: object
definitions:
  StudentSwag:
    items:
      type: object
    required:
      - name
    properties:
      id:
        type: integer
        example: 4
      name:
        type: string
        example: nazwa
      passportName:
        type: string
        example: paszport
  StudentSwagList:
    items:
      type: array
    properties:
      id:
        type: integer
        example: 12
      name:
        type: string
        example: nazwaFromList
      passportName:
        type: string
        example: paszportFromList