/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package app.swagger.api;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import app.swagger.model.StudentSwag;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.io.IOException;
import java.util.Optional;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-28T21:40:49.806+01:00")

@Api(value = "postStudentSwagSwaggerWithResponse", description = "the postStudentSwagSwaggerWithResponse API")
public interface PostStudentSwagSwaggerWithResponseApi {

    Logger log = LoggerFactory.getLogger(PostStudentSwagSwaggerWithResponseApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "", nickname = "postStudentSwagSwaggerWithResponsePost", notes = "", response = StudentSwag.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok from Post regards", response = StudentSwag.class) })
    @RequestMapping(value = "/postStudentSwagSwaggerWithResponse",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<StudentSwag> postStudentSwagSwaggerWithResponsePost(@ApiParam(value = "Consumes from Post."  )  @Valid @RequestBody StudentSwag user) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"name\" : \"nazwa\",  \"id\" : 4,  \"passportName\" : \"paszport\"}", StudentSwag.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default PostStudentSwagSwaggerWithResponseApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
